project_id = "qwgsplcqyongfsqdjrme"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-debug-login]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-invitation-request]
verify_jwt = false

[functions.upload-to-minio]
verify_jwt = false

[functions.send-reuse-alerts]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.sms-automation-run]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.process-whatsapp-schedule]
verify_jwt = false

[functions.sync-whatsapp-instances]
verify_jwt = false

[functions.brdid-api]
verify_jwt = false

[functions.baseoff-external-query]
verify_jwt = false

[functions.radar-opportunities]
verify_jwt = false

[functions.autolead-worker]
verify_jwt = false

[functions.joinbank-proxy]
verify_jwt = false

[functions.sms-status-callback]
verify_jwt = false

[functions.sms-check-status]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-voices]
verify_jwt = false

[functions.voicer-ai-variations]
verify_jwt = false

[functions.voicer-generate-example]
verify_jwt = false

[functions.voicer-enhance-text]
verify_jwt = false

[functions.novavida-get-token]
verify_jwt = false

[functions.novavida-consulta]
verify_jwt = false

