ALTER TABLE public.autolead_jobs
  ADD COLUMN IF NOT EXISTS sms_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sms_template TEXT,
  ADD COLUMN IF NOT EXISTS sms_sent INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sms_failed INTEGER NOT NULL DEFAULT 0;